spring.application.name=policia-backend

# ==========================================
# BASE DE DATOS
# ==========================================

# URL de conexi\u00f3n a MySQL
spring.datasource.url=${DB_URL}
# Usuario de MySQL
spring.datasource.username=${DB_USERNAME}
# Contrase\u00f1a de MySQL
spring.datasource.password=${DB_PASSWORD}

spring.config.import=optional:classpath:application-local.properties


# ==========================================
# JPA / HIBERNATE
# ==========================================

#spring.jpa.hibernate.ddl-auto=create
# Actualiza las tablas seg\u00fan las entidades Java
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en consola
spring.jpa.show-sql=true
# Formatea las consultas SQL para que sean legibles
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# CONFIGURACION CORS (FRONTEND)
# ==========================================

# Origen permitido para las peticiones HTTP desde el frontend (Vaadin)
cors.allowed-origin=http://localhost:8081


logging.level.org.springframework.security=DEBUG