# ==========================================
# CONEXI\u00d3N MYSQL - LOCAL
# ==========================================

# Cambiar el puerto de MySQL y la contrase\u00f1a.
# Cambiar el nombre de este archivo a: application-local.properties

DB_URL=jdbc:mysql://localhost:PUERTO/policia_db
DB_USERNAME=root
DB_PASSWORD=TU_PASSWORD

